---
title: "Climate Changes Affect on Plant Species in Arizona"
author: "Lukas Robinson"
date: "3/11/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = FALSE, message=FALSE, warning=FALSE)
```

## R Markdown

## Abstract
Climate change here on Earth is at an alarming stage, with a steady increase in atmospheric carbon dioxide affecting how plants photosynthesis, to the unbalanced situations in climatic conditions, some places prolonged droughts and in others increased flooding. These issues are causing major problems for plant species worldwide. Climate change is defined as a long-term change in the average weather patterns that have come to define Earth’s local, regional and global climates. Just with this definition, we can hypothesis that as climate change slowly changes Earth’s local, regional and global climates plant species will be affected in some way. In this research project, I will be answering how climate change is affecting these plant species based on their plant distribution over time. To define plant distribution I will be looking at three different time periods and three common plant species found at different elevations in Arizona then comparing the abundance and distribution of those plant species in that area. I will be using the Botanical Information and Ecology Network (BIEN) package to look at all of the data and the BIEN data will be the data presented.

## Introduction

## Methods

### Data Acquisition

For this project, I obtained data from the Botanical Information and Ecology Network (BIEN, 2021). This data was acquired using the R package known as BIEN (Maitner, 2020). BIEN was used to obtain information about plant distribution and abundance over numerous years. No special access was required to access this resource I just needed to download the package into R Studio before looking at the data. Since the data from the BIEN package is so large I narrowed down my search for a good research project by searching for three plant species using information found from azstateparks.com. 

### Data Preparation

Data was first prepared for analysis by filtering through all the plant species in the BIEN package to only the three plant species that I wanted to look at. 

Once I filtered out my three species I then bound these three data sets into one data set and simplified that to only have the categories I needed for my research. The categories include species, date_collected, year, and geometry. By doing this it helped me better understand how large my sample size will be for this experiment.

After I created this new data set, I filtered out the two states that I will be looking at, California and Arizona. Once that was done I graphed the data into three separate rows and columns.

## Results

## Discussion

## Literature Cited

1. Brian Maitner (2020). BIEN: Tools for Accessing the
   Botanical Information and Ecology Network Database. R
   package version 1.2.4.
   https://CRAN.R-project.org/package=BIEN
   
2. RStudio Team (2020). RStudio: Integrated Development Environment for
   R. RStudio, PBC, Boston, MA URL http://www.rstudio.com/
   
   
## References





